### ISSUE TITLE
Unable to load dynamic library

### ISSUE THREAD

**Issue by lrstndm** [Azure/msphpsql#101]
Environment:
PHP 7.0.7
Centos 7.2

I just downloaded the php_sqlsrv_7_ts.so and placed the file in my extension_dir. I also updated the php.ini with the extension. But when I execute the following code on my linux server: `php -v` I get the following error. Is this a wrong compiled so file?

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/php_sqlsrv_7_ts.so' - /usr/lib64/php/modules/php_sqlsrv_7_ts.so: undefined symbol: SQLGetDiagField in Unknown on line 0
PHP 7.0.7 (cli) (built: May 28 2016 07:53:22) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by meet-bhagdev** [comment]
@lrstndm How did you install php? Did you do it via source or package manager?

**Comment by lrstndm** [comment]
using the following repo: https://webtatic.com/packages/php70/ . is there a better way to do it?

**Comment by meet-bhagdev** [comment]
Sounds correct to me. Did you install the ODBC Driver on your CentOS machine? What version did you install?

**Comment by lrstndm** [comment]
when I run the `yum list unixodbc` I get the following line returned

unixODBC.i686    2.3.1-11.el7

**Comment by meet-bhagdev** [comment]
That seems like the unixODBC version. Did you download the Microsoft ODBC Driver? You can confirm this by using the following: `odbcinst -q -d -n "ODBC Driver 13 for SQL Server"`
What is the result of using that prompt?

**Comment by lrstndm** [comment]
output is: `odbcinst: SQLGetPrivateProfileString failed with .`

**Comment by meet-bhagdev** [comment]
Seems like you do not have the Microsoft ODBC Driver installed. Did you install it? If not you can install it using the following commands on a clean **CentOS 7.x machine**: 
```
    sudo su
    wget https://gallery.technet.microsoft.com/ODBC-Driver-13-for-SQL-8d067754/file/153653/4/install.sh
    sh install.sh
```

Once you do this, let me know what output do you get when you type this `odbcinst -q -d -n "ODBC Driver 13 for SQL Server"` in the terminal

**Comment by lrstndm** [comment]
I just run the code you send and I reveiced the following output:

> [ODBC Driver 13 for SQL Server]
> Description=Microsoft ODBC Driver 13 for SQL Server
> Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
> Threading=1
> UsageCount=1

**Comment by meet-bhagdev** [comment]
The way you load the driver in the php.ini file is like this: extension=php_sqlsrv_7_ts.so or extension=php_sqlsrv_7_nts.so
Check out our instructions: https://github.com/Azure/msphpsql/tree/PHP-7.0-Linux#enable-the-drivers
Could you shed some light on why you are using Driver=..?

**Comment by lrstndm** [comment]
sorry for the misscommunication. I adder the following line to the php.in `extension=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so`
That is the path from the driver value.

**Comment by kubacode** [comment]
@lrstndm you shouldn't be loading libmsodbcsql-13.0.so in your PHP.ini file.

Can you replace
```
extension=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so
```
with 
```
extension=php_sqlsrv_7_nts.so
```

**Comment by lrstndm** [comment]
I cannot find the `php_sqlsrv_7_nts.so` file, but i have the `php_sqlsrv_7_ts.so` file from this repo.

I updated the `php.ini` file with the following line `extension=php_sqlsrv_7_ts.so`. I also tried with the full path: `extension=/usr/lib64/php/modules/php_sqlsrv_7_nts.so`

But I still get the same error when I run `php -v`

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/php_sqlsrv_7_ts.so' - /usr/lib64/php/modules/php_sqlsrv_7_ts.so: undefined symbol: SQLGetDiagField in Unknown on line 0

**Comment by meet-bhagdev** [comment]
Can you try running this and share what your output is? `odbcinst -q -d -n "ODBC Driver 13 for SQL Server"`

**Comment by josevieirame** [comment]
I have the same issue in centos 7 and the 

> odbcinst -q -d -n "ODBC Driver 13 for SQL Server"

results in

> Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
> Threading=1
> UsageCount=2

**Comment by meet-bhagdev** [comment]
@lrstndm @josevieirame Can you follow the instructions here: https://github.com/Azure/msphpsql/blob/PHP-7.0-Linux/LinuxTutorial.md. That should resolve this issue.
