### ISSUE TITLE
Binaries outdated

### ISSUE THREAD

**Issue by marbleman** [Azure/msphpsql#103]
Would like to test the RC but the binaries haven't been updated with the RC version, they are 2 months old...

**Comment by meet-bhagdev** [comment]
Hello @marbleman , you can find the latest binaries here: https://github.com/Azure/msphpsql/releases

Cheers,
Meet

**Comment by marbleman** [comment]
Thx a lot! I found the old link on https://github.com/Azure/msphpsql/tree/PHP-7.0 under "Binaries" 
Maybe its worth updating that one...
