### ISSUE TITLE
Unable to load extension on Ubuntu 16.04

### ISSUE THREAD

**Issue by Angel-Gonzalez** [Azure/msphpsql#104]
I have a fresh install of Ubuntu 16.04, nginx 1.1, php7-fpm. Added the extension for my distro but php-fpm was unable to load. `systemctl status php7.0-fpm.service` give me this out put:
php7.0-fpm.service - The PHP 7.0 FastCGI Process Manager
Loaded: loaded (/lib/systemd/system/php7.0-fpm.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code)
Docs: man:php-fpm7.0(8)
Process: 1785 ExecStart=/usr/sbin/php-fpm7.0 --nodaemonize --fpm-config /etc/php/7.0/fpm/php-fpm.conf (code=exited, status=127) Main PID: 1785 (code=exited, status=127)
jul 01 08:30:09 : Starting The PHP 7.0 FastCGI Process Manager...
jul 01 08:30:09 : **/usr/sbin/php-fpm7.0: **symbol lookup error: /usr/lib/php/php_pdo_sqlsrv_7_ts.so: undefined symbol: SQLAllocHandle****
jul 01 08:30:09 : php7.0-fpm.service: Main process exited, code=exited, status=127/n/a
jul 01 08:30:09 : Failed to start The PHP 7.0 FastCGI Process Manager.
jul 01 08:30:09 : php7.0-fpm.service: Unit entered failed state.
jul 01 08:30:09 : php7.0-fpm.service: Failed with result 'exit-code'.
getting rid of the extension fix the fpm loading problem, but i need to connect with sqlserver. Any suggestions?

**Comment by meet-bhagdev** [comment]
Hello @Angel-Gonzalez Just checking it to make sure you are good to go with this issue as you have closed it. Do you still need any assistance?

**Comment by meet-bhagdev** [comment]
@Angel-Gonzalez Glad to hear. Any reason why you had to install the Sybase extension? Did the Microsoft PHP Driver extension on Linux not work for you?

**Comment by Angel-Gonzalez** [comment]
It works partially, i'm getting this error **Invalid sql_display_size** when i try to fetch the results of some queries, until now i'm unable to fix this error.
query example:
```
 SELECT  CodigoArticulo,DescripcionArticulo AS LineTitle, DescripcionLinea AS Descripcion,
CabeceraDeGrupoImp AS Tipo,NumGrupoImpresionSH AS Grupo,cast([%Descuento] AS DECIMAL(18,2)) AS Descuento,
cast(UnidadesPedidas AS INT) AS Unidades, cast(Precio AS DECIMAL(18,2)) AS Precio, 
GrupoIva, cast([%Iva] AS DECIMAL(18,2)) AS PIva, 
cast(ImporteNeto AS DECIMAL(18,2)) AS Importe, cast(TotalIva AS DECIMAL(18,2)) AS Iva
FROM LineasOfertaCliente 
WHERE NumeroOferta = ? ORDER BY orden
```
Sybase also has plenty bugs with nvarchar type, procedures, and others... so i'm trying to fix the sql_display_size error  to use Microsoft PHP Driver extension since it's more stable than Sybase.
Note: The queries works perfect in MS SQL Server manager, also to this pdo extension under windows, wich works out of the box just fine.

**Comment by Angel-Gonzalez** [comment]
I figure out a work around the sql_display_size, the columns type text triggers the error, so i cast a varchar on each column of this type. Here is an example 
`cast(MyTextColumn as varchar(max))`
