### ISSUE TITLE
Pre-compiled PHP7 binaries not available

### ISSUE THREAD

**Issue by rloone** [Azure/msphpsql#105]
But it's returning a very cool 404 page that I'd not seen before :-)

**Comment by meet-bhagdev** [comment]
@rloone You should find them in the releases here: https://github.com/Azure/msphpsql/releases. Let me know if you have further questions.

**Comment by rloone** [comment]
Thanks! - You may wish to update the page at [https://github.com/Azure/msphpsql/tree/PHP-7.0](https://github.com/Azure/msphpsql/tree/PHP-7.0) it has a link that references somewhere else.

**Comment by meet-bhagdev** [comment]
Doing it right away!! :)
