### ISSUE TITLE
Binding string parameter as PDO::PARAM_INPUT_OUTPUT does not work.

### ISSUE THREAD

**Issue by karol-pilch** [Azure/msphpsql#108]
Using string parameters as `PARAM_INPUT_OUTPUT` produces unexpected results when calling a stored procedure, and in some situations crashes PHP completely. It never works as expected when results are fetched. Here's the table of the behaviour of the string input / output parameter in various situations:

<table>
  <tr>
    <th></th>
    <th colspan="2"><strong>Outcome</strong></th>
  </tr>
  <tr>
    <td><strong>Stage</td>
    <td><strong>Parameter included in SELECT</strong></td>
    <td><strong>Parameter NOT included in SELECT</strong></td>
  </tr>
  <tr>
    <td>Before execute()</td>
    <td>Unchanged</td>
    <td>Unchanged</td>
  </tr>
  <tr>
    <td>After execute()</td>
    <td>\u0000 added every second character</td>
    <td>\u0000 added every second character</td>
  </tr>
  <tr>
    <td colspan="3" style="text-align: center;"><strong>With fetch()</strong></td>
  </tr>
  <tr>
    <td>After fetch()</td>
    <td>Unchanged (back to<br>  original)</td>
    <td>Unchanged (back to original)</td>
  </tr>
  <tr>
    <td>After closeCursor()</td>
    <td>Error 500 (C:\Program Files\PHP\v7.0\php-cgi.exe - The FastCGI process exited unexpectedly)</td>
    <td>Unchanged (back to original)</td>
  </tr>
  <tr>
    <td colspan="3" style="text-align: center;"><strong>Without fetch()</strong></td>
  </tr>
  <tr>
    <td>After closeCursor()</td>
    <td>Changed correctly</td>
    <td>Changed correctly</td>
  </tr>
</table>

The stored procedure:

```SQL
ALTER PROCEDURE [dbo].[sp_Test]
	@pOutputString nvarchar(255) = NULL OUTPUT,
	@pOutputNumber bigint = NULL OUTPUT,
	@pInputString nvarchar(255) = '',
	@pInputNumber bigint = 0
AS
BEGIN
	SET NOCOUNT ON;
	SELECT @pOutputString = 'You have entered "' + @pInputString + '" as the input.'
	SELECT @pOutputNumber = 666 - @pInputNumber

	SELECT 
		'Procedure completed' AS [Result], 
		@pInputNumber as [InputNumber], 
		@pInputString AS [InputString], 

		-- The following two were commented out for 'Parameter NOT included in SELECT' outcomes.
		@pOutputNumber AS [OutputNumber], 
		@pOutputString AS [OutputString]
END
```

And the PHP used for testing:
```PHP
<?php

header('Content-Type: text/plain');

$dsn = "<our DSN>";
$username = "<user name>";
$password = "<password>";

print("Getting database...\n");
try {
  $pdo = new PDO($dsn, $username, $password);
}
catch(PDOException $e) {
  print("Error: " . $e->getMessage() . "\n");
}

try {
	$sql = "
EXEC sp_Test 
	@pOutputString = :out_string, 
	@pOutputNumber = :out_number, 
	@pInputString = :in_string,
	@pInputNumber = :in_number
";
	
	$query = $pdo->prepare($sql);

	$in_string = 'Hello world!';
	$in_number = 600;

	$out_string = '';
	// If it's left as an empty string, even weirder things are happening.
	for ($i = 0; $i <= 255; $i++) {
		$out_string .= ' ';
	}
	$out_number = 0;

	print("\n" . json_encode(array(
		'Output string' => $out_string,
		'Output number' => $out_number,
		'Input string' => $in_string,
		'Input number' => $in_number
	), JSON_PRETTY_PRINT));
	
	$query->bindParam(':in_string', $in_string);
	$query->bindParam(':in_number', $in_number);

	$query->bindParam(':out_string', $out_string, PDO::PARAM_STR|PDO::PARAM_INPUT_OUTPUT, 255);
	$query->bindParam(':out_number', $out_number, PDO::PARAM_INT|PDO::PARAM_INPUT_OUTPUT, 4);

	print("\nExecuting query...");
	$query->execute();

	print("\n" . json_encode(array(
		'Output string' => $out_string,
		'Output number' => $out_number,
		'Input string' => $in_string,
		'Input number' => $in_number
	), JSON_PRETTY_PRINT));

	print("\nFetching results...");
	$results = $query->fetchAll();
	print("\nResults: " . print_r($results, TRUE));

	print("\n" . json_encode(array(
		'Output string' => $out_string,
		'Output number' => $out_number,
		'Input string' => $in_string,
		'Input number' => $in_number
	), JSON_PRETTY_PRINT));

	print("\nClosing cursor...");
	$query->closeCursor();

	print("\n" . json_encode(array(
		'Output string' => $out_string,
		'Output number' => $out_number,
		'Input string' => $in_string,
		'Input number' => $in_number
	), JSON_PRETTY_PRINT));
}
catch(Error $e) {
  print("Error: " . $e->getMessage() . "\n");
}
```

To produce the table of outcomes, I was commenting out some parts of the code, both in the stored procedure, and in the PHP script.

When the server returns error 500, the catch block is not executed and no errors are logged in the PHP log even though error reporting is set to `E_ALL`.

I'm using PHP 7.0.8 with sqlsrv extension 4.0.8610.3 (the latest).

**Comment by meet-bhagdev** [comment]
@karol-pilch Did you run into the same issue with our PHP 5.6 driver?

**Comment by karol-pilch** [comment]
Off the top of my head, the 5.6 driver was also filling in the string with
\u0000 characters, but would be updated with the changed string from the
procedure when using fetch(), and most importanty it wouldn't cause the
error 500.

**Comment by meet-bhagdev** [comment]
@karol-pilch We believe we fixed this issue in our latest release: https://github.com/Azure/msphpsql/releases/tag/4.1.0.
Can you help us validate?

**Comment by karol-pilch** [comment]
Yep, it looks fine now. As you said in the release notes, the string variable bound to the output parameter only gets substituted after the call to `closeCursor()`, but at least the script doesn't die.

Thanks very much!
