### ISSUE TITLE
PHP7.0-Linux causes segmenation fault when running Doctrine DBAL test suite

### ISSUE THREAD

**Issue by xalopp** [Azure/msphpsql#109]
When I run the Doctrine [DBAL](https://github.com/doctrine/dbal) test suite I get a segmentation fault.

```
ubuntu@ubuntu-xenial:~/dbal$ ./vendor/bin/phpunit --configuration tests/travis/sqlsrv.travis.xml
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

...............................................SSS...........   61 / 3867 (  1%)
.SS..............S.......SS...S.....S.SSS..........S....SS..S  122 / 3867 (  3%)
SS......SSS..............SS...SSS.........SS...S............S  183 / 3867 (  4%)
.S..............................................SSSS.........  244 / 3867 (  6%)
..........S...S..S..S........................................  305 / 3867 (  7%)
......E.EE......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSegmentation fault (core dumped)
```

For the test setup, I use this [vagrant box](https://github.com/xalopp/vagrant-php7sqlsrv) to setup PHP7 and the Microsoft SQLSRV driver for Linux.

I use the SQLSRV Driver `Ubuntu1604/php_sqlsrv_7_ts.so `
and the PHP Packages provided by [ondrej/php](http://ppa.launchpad.net/ondrej/php/ubuntu)
```
PHP 7.0.8-4+deb.sury.org~xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-4+deb.sury.org~xenial+1, Copyright (c) 1999-2016, by Zend Technologies
```

The test are run against a MS SQL Server 2016.

**Comment by xalopp** [comment]
I tested it with the updated driver `binaries/ubuntu1604_binaries/php_sqlsrv_7_nts.so`, unfortunately it's still segfaulting :-(

Output from `php -i`
```
sqlsrv

sqlsrv support => enabled
ExtensionVer => 4.0.1.0

Directive => Local Value => Master Value
sqlsrv.ClientBufferMaxKBSize => 10240 => 10240
sqlsrv.LogSeverity => 0 => 0
sqlsrv.LogSubsystems => 0 => 0
sqlsrv.WarningsReturnAsErrors => On => On
```

**Comment by meet-bhagdev** [comment]
We will look into this. Can you confirm that the ODBC Driver is installed successfully?

**Comment by xalopp** [comment]
```
odbcinst -q -d -n "ODBC Driver 13 for SQL Server"
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
Threading=1
UsageCount=2
```

Changing my connection settings to
```
$serverName = "tcp:192.168.56.102,1433";
$connectionOptions = array("Database" => "AdventureWorks2016CTP3", "Uid" => "test", "PWD" => 'test');
```
`php sample/sqlsrv_sample.php ` runs without failure:

```
	 <h1> First 10 results are : </h1>
	 AW00000001<br/>AW00000002<br/>AW00000007<br/>AW00000019<br/>AW00000020<br/>AW00000037<br/>AW00000038<br/>AW00000043<br/>AW00000055<br/>AW00000056<br/> 
```

I've the feeling that the issues may be in the code handling errors from the database

` ./vendor/bin/phpunit --configuration tests/travis/sqlsrv.travis.xml  --filter SQLServerSchemaManagerTest::testRenameIndexUsedInForeignKeyConstraint 
` runs fine, but repeating the test, which will produce an regular error because of lacking test cleanup, will end with a segault:

```
 ./vendor/bin/phpunit --configuration tests/travis/sqlsrv.travis.xml  --filter SQLServerSchemaManagerTest::testRenameIndexUsedInForeignKeyConstraint --repeat 200
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

.EEEEEEEEEEEEEEEEEEEEEEESegmentation fault (core dumped)
```

**Comment by xalopp** [comment]
@meet-bhagdev version 4.0.2 of the Linux drivers solves this issue.

**Comment by meet-bhagdev** [comment]
Awesome! Glad to hear :) I will close this issue. Feel free to re-open this if needed.
