### ISSUE TITLE
PHP Extension not loading

### ISSUE THREAD

**Issue by boredom2** [Azure/msphpsql#117]
Hi there,

thanks for making this finally happen :)
Sadly, Im currently not able yet to make this work, but I am close. The ODBC Driver is installed and working fine, the Extension is on the right place and PHP tried to load it - but fails.

Here are the Details:
- Ubuntu 16.04 with installed ODBC
- PHP 7.0, installed via PPA (https://launchpad.net/~ondrej/+archive/ubuntu/php), so I did not compile from source
- copied the downloaded (TS with PDO) .so File to /usr/lib/php/20151012
- PHP Startup stated: "unable to load dynamic library...: undefined symbol: executor_globals_id in Unknown on line 0"
=> I think, this has something to do with Version Management or Compilation Issues, maybe Place or Syntax is wrong. Can you maybe give me a hint, whats wrong here?

Thanks a lot,
Christoph

**Comment by meet-bhagdev** [comment]
Hello Christoph, glad to hear you are trying out our preview binaries. If you downloaded PHP from PPA, you got a non-thread safe PHP and has to use the NTS drivers. Can you confirm and retry by uploading the nts binaries?
Thanks,
Meet

**Comment by boredom2** [comment]
Thansk for the quick reply. I tried that also already - if I try compiling with _nts.so, I get "invalid ELF header in Unknown on line 0" - different error, but not really better.

**Comment by meet-bhagdev** [comment]
Understood. Can you confirm that the ODBC Driver is installed using this command `odbcinst -q -d -n "ODBC Driver 13 for SQL Server"
`
Did you add this extention so the php.ini file? Check out our tutorial here: https://github.com/Azure/msphpsql/blob/PHP-7.0-Linux/LinuxTutorial.md

**Comment by boredom2** [comment]
Oh yes, this is working, it correctly returns the desired Strings as mentioned in the Docs.
And yes, I added an extra Config for that and from "display_startup_errors", I know whats going wrong there. I attach a screenshot of the SSH just to make sure we have all informations you may need...

![odcb](https://cloud.githubusercontent.com/assets/409857/17266372/e63bf706-5629-11e6-88ab-79004a350099.JPG)

**Comment by boredom2** [comment]
The new Release 4.0.2 is sadly not fixing this issue. Any news on this "ELF header invalid" problem here?

**Comment by super-vip** [comment]
I also ask a question:
Method 2: Using the PHP source. 
But:
1. pdo_sqlsrv and sqlsrv can be found using "php -m".
2. See the phpinfo display: PDO drivers oci, SQLite mysql. No pdo_sqlsrv and sqlsrv.
3. Test tips: Fatal error: Uncaught PDOException: could not find driver in ......

**Comment by boredom2** [comment]
I would really love to make this work, but I dont know, what else I can check in order to make it work.
I noticed, that php7.0-odbc was not installed so far, so I added that also.
But sadly, PHP does not load the extension, it only states (in startup errrors": invalid ELF header in Unknown on line 0.
Is there a Place, where I can find out more whats going wrong here in order to get into make this work :)
Thanks!

**Comment by xalopp** [comment]
Would it help you to peek from a working Ubuntu installation?
I've create a puppetized Vagrant Box to test the sqlsrv driver: https://github.com/xalopp/vagrant-php7sqlsrv

Maybe you can find out whats going wrong by comparing this with your setup?

**Comment by meet-bhagdev** [comment]
@boredom2 Can you share if you are using the thread safe or the non thread safe version of the driver? It would also be a good idea to make sure that the php.ini is not malformed. http://stackoverflow.com/questions/17910327/warning-when-i-run-a-php-script
Are you using Apache? If yes, can you restart your server and let us know if you still get this issue.

**Comment by boredom2** [comment]
The latest Update make the magic happen - everythings working without any issues.
Thanks a lot for your work!

**Comment by meet-bhagdev** [comment]
Awesome :) Glad to hear.
