### ISSUE TITLE
Fatal error: Uncaught PDOException: could not find driver in

### ISSUE THREAD

**Issue by super-vip** [Azure/msphpsql#118]
I also ask a question:
Method 2: Using the PHP source.
But:
1. pdo_sqlsrv and sqlsrv can be found using "php -m".
2. See the phpinfo display: PDO drivers oci, SQLite mysql. No pdo_sqlsrv and sqlsrv.
3. Test tips: Fatal error: Uncaught PDOException: could not find driver in ......

Other information:
OS: CentOS Linux release 7.2.1511 (Core)
Apache Version: Apache/2.4.23 (Unix) OpenSSL/1.0.2h PHP/7.0.9

**Comment by meet-bhagdev** [comment]
Hello @super-vip 
Can you confirm that you installed the ODBC Driver and PHP Driver for SQL Server based on the steps listed here: https://github.com/Azure/msphpsql/blob/PHP-7.0-Linux/LinuxTutorial.md
Additionally you can confirm if the ODBC Driver is installed by using this command:
`odbcinst -q -d -n "ODBC Driver 13 for SQL Server"`

**Comment by super-vip** [comment]
@meet-bhagdev 
Thanks for your response.

[root@dev ~]# odbcinst -q -d -n "ODBC Driver 13 for SQL Server"
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
Threading=1
UsageCount=2

[root@dev ~]# php -m
[PHP Modules]
......
PDO
pdo_mysql
PDO_OCI
PDO_ODBC
pdo_sqlite
pdo_sqlsrv
......
sqlsrv
......

[Zend Modules]
Zend OPcache

[root@dev ~]# php -v
PHP 7.0.9 (cli) (built: Aug  8 2016 12:22:02) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.9, Copyright (c) 1999-2016, by Zend Technologies

[root@dev ~]# php -i
......
PDO
PDO support => enabled
PDO drivers => oci, odbc, sqlite, mysql, sqlsrv
......
PDO_ODBC
PDO Driver for ODBC (unixODBC) => enabled
ODBC Connection Pooling => Enabled, strict matching
......
pdo_sqlsrv
pdo_sqlsrv support => enabled
ExtensionVer => 4.0.2.0
Directive => Local Value => Master Value
pdo_sqlsrv.client_buffer_max_kb_size => 10240 => 10240
pdo_sqlsrv.log_severity => 0 => 0
......
sqlsrv
sqlsrv support => enabled
ExtensionVer => 4.0.2.0
Directive => Local Value => Master Value
sqlsrv.ClientBufferMaxKBSize => 10240 => 10240
sqlsrv.LogSeverity => 0 => 0
sqlsrv.LogSubsystems => 0 => 0
sqlsrv.WarningsReturnAsErrors => On => On
......

[root@dev ~]# cat /web/test.php 
<?php
try {
	$db = new PDO ( "sqlsrv:server=192.168.100.101,1433;database=family", "sa", "110110" );
    echo "PHP Connect to " . "SQL Server" . " Database successfully<br />";
} catch ( PDOException $e ) {
	echo 'The connection failed: ' . $e->getMessage ();
	}
?>

result:
The connection failed: could not find driver.

[root@dev ~]# cat /usr/local/php/etc/php.ini
......
date.timezone = PRC
include_path = "/usr/local/php/lib/php"
extension=php_sqlsrv_7_nts.so
extension=php_pdo_sqlsrv_7_nts.so
zend_extension=opcache.so

**Comment by super-vip** [comment]
Latest test findings:
The use of CLI and PHP-cgi can run normally.

[root@dev ~]# php /web/pdo-test.php 
The DSN connection string: <i>sqlsrv:server=192.168.100.101,1433;database=family</i><br />PHP Connect to SQL Server Database successfully<br /><br />

[root@dev ~]# php-cgi /web/pdo-test.php 
X-Powered-By: PHP/7.0.9
Content-type: text/html; charset=UTF-8
The DSN connection string: <i>sqlsrv:server=192.168.100.101,1433;database=family</i><br />PHP Connect to SQL Server Database successfully<br /><br />

**Comment by meet-bhagdev** [comment]
@super-vip does this mean we are good to go? Are you able to connect successfully or do you still need help?

**Comment by super-vip** [comment]
@meet-bhagdev 
From the test results, it seems a bit off the subject of discussion.
Because these dynamic modules can work properly in CLI and cgi.
But cannot be loaded in apache2handler.
Also led to 'phpinfo' cannot display sqlsrv information.
Either PHP compiler is a problem, or the HTTPD compiler is a problem, or the module conflict,or compatibility problems...
Sorry,my English is poor.The words do not convey the thought.
Well,this problem makes me get headache.....
I don't know what to do next ......

**Comment by super-vip** [comment]
[root@dev ~]# tail -13 /usr/local/php/etc/php.ini 
date.timezone = PRC
include_path = "/usr/local/php/lib/php"
extension=pdo.so
extension=oci8.so
extension=pdo_oci.so
extension=pdo_mysql.so
extension=mysqli.so
extension=pdo_odbc.so
extension=sqlite3.so
extension=pdo_sqlite.so
extension=php_sqlsrv_7_nts.so
extension=php_pdo_sqlsrv_7_nts.so
zend_extension=opcache.so

`[root@dev web]# cat pdo-test.php 
<?php
$dbms = strtolower ( trim ( 'mssql' ) ); // toggle case
$dbhost = trim ( '192.168.100.101' ); // database host
$dbport = trim ( '1433' ); // database port
$dbname = trim ( 'family' ); // database name
$dbuser = trim ( 'sa' ); // database user
$dbpass = trim ( '110110' ); // database password
$dbcharset = trim ( 'utf8' ); // database charset

if ($dbms == 'mysql') {
	$dsn = "mysql:host=$dbhost;port=$dbport;dbname=$dbname;charset=$dbcharset";
	echo "The DSN connection string: <i>" . $dsn . '</i>';
	echo '<br />';
} elseif ($dbms == 'oracle') {
	$dsn = "oci:dbname=//$dbhost:$dbport/$dbname;charset=$dbcharset";
	echo "The DSN connection string: <i>" . $dsn . '</i>';
	echo '<br />';
} elseif ($dbms == 'mssql') {
	$dsn = "sqlsrv:server=$dbhost,$dbport;database=$dbname";
	echo "The DSN connection string: <i>" . $dsn . '</i>';
	echo '<br />';
} else {
	exit ( 'The database type is not supported.' );
}

try {
	$db = new PDO ( $dsn, $dbuser, $dbpass );
	if ($dbms == 'mysql') {
		echo "PHP Connect to " . "Mysql" . " Database successfully<br />";
		echo '<br />';
	} elseif ($dbms == 'oracle') {
		echo "PHP Connect to " . "Oracle" . " Database successfully<br />";
		echo '<br />';
	} elseif ($dbms == 'mssql') {
		echo "PHP Connect to " . "SQL Server" . " Database successfully<br />";
		echo '<br />';
		$clientinfo = $db->getAttribute ( constant ( "PDO::ATTR_CLIENT_VERSION" ) );
		$serverinfo = $db->getAttribute ( constant ( "PDO::ATTR_SERVER_INFO" ) );
		echo 'DB Server Info: ' . '<br /><i>';
		foreach ( $serverinfo as $server_key => $server_value ) {
			echo $server_key . '=>' . $server_value . '<br />';
		}
		echo '</i>';
		echo 'DB Client Info: ' . '<br /><i>';
		foreach ( $clientinfo as $client_key => $client_value ) {
			echo $client_key . '=>' . $client_value . '<br />';
		}
		echo '</i>';
	}
} catch ( PDOException $e ) {
	if ($dbms == 'mysql') {
		exit ( "The connection failed: " . iconv ( "GB2312", "UTF-8", $e->getMessage () ) . '<br />' );
	} elseif ($dbms == 'oracle') {
		exit ( "The connection failed: " . $e->getMessage () . '<br />' );
	} elseif ($dbms == 'mssql') {
		exit ( "The connection failed: " . $e->getMessage () . '<br />' );
	} else {
		echo 'The connection failed: ' . $e->getMessage ();
	}
}

?>`

Test result:

The DSN connection string: sqlsrv:server=192.168.100.101,1433;database=family
PHP Connect to SQL Server Database successfully

DB Server Info:
CurrentDatabase=>family
SQLServerVersion=>13.00.1601
SQLServerName=>WORK-PC
DB Client Info:
DriverName=>libmsodbcsql-13.0.so.0.0
DriverODBCVer=>03.52
DriverVer=>13.00.0000
ExtensionVer=>4.0.2.0

Test phpinfo():
![pdo](https://cloud.githubusercontent.com/assets/19517568/17504826/e2c3535a-5e2e-11e6-9f27-5e65b5bf1c73.png)
![pdo-sqlsrv](https://cloud.githubusercontent.com/assets/19517568/17504827/e2fd8462-5e2e-11e6-901a-bb93999b8bda.png)
![sqlsrv](https://cloud.githubusercontent.com/assets/19517568/17504833/eabbe9dc-5e2e-11e6-9228-036bcb623bc0.png)

After numerous attempts, finally solved the problem.
The reason may be that some of the modules in the Apache are not enabled.

**Comment by meet-bhagdev** [comment]
Awesome! @super-vip I am glad that did the trick. Closing this issue for now, feel free to re-open if you need to

**Comment by nguyentranbaoanh** [comment]
Hi all,

Can you tell me how to get the 
extension=php_sqlsrv_7_nts.so
extension=php_pdo_sqlsrv_7_nts.so
And tell me how to connect with sqlsrv. This problem took me 2 weeks.

Thanks,

**Comment by meet-bhagdev** [comment]
@nguyentranbaoanh check out this blog: https://blogs.msdn.microsoft.com/sqlphp/2016/10/10/getting-started-with-php-7-sql-server-and-azure-sql-database-on-linux-ubuntu-with-apache/

**Comment by JoseReneA** [comment]
when we use PLESK, what is the route to set the drivers?
