### ISSUE TITLE
php --re sqlsrv returns warnings.

### ISSUE THREAD

**Issue by v-mabarw** [Azure/msphpsql#12]
Hi.  
  
Using the official PHP V5.3.2 and php_sqlsrv_53_nts_vc9.dll results in some
warnings when using --ri.  
  
Even tried removing the ini file (-n) ...  
  
php -n -d extension_dir=c:\php5\ext -d extension=php_sqlsrv_53_nts_vc9.dll
--re sqlsrv  
  
results in ...  
  
Warning: Internal error: Cannot find extension function SQLSRV_PHPTYPE_STREAM
in global function table in Unknown on line 0  
  
Warning: Internal error: Cannot find extension function SQLSRV_PHPTYPE_STRING
in global function table in Unknown on line 0  
  
Warning: Internal error: Cannot find extension function SQLSRV_SQLTYPE_BINARY
in global function table in Unknown on line 0  
  
Warning: Internal error: Cannot find extension function SQLSRV_SQLTYPE_CHAR in
global function table in Unknown on line 0  
  
Warning: Internal error: Cannot find extension function SQLSRV_SQLTYPE_DECIMAL
in global function table in Unknown on line 0  
  
Warning: Internal error: Cannot find extension function SQLSRV_SQLTYPE_NCHAR
in global function table in Unknown on line 0  
  
Warning: Internal error: Cannot find extension function SQLSRV_SQLTYPE_NUMERIC
in global function table in Unknown on line 0  
  
Warning: Internal error: Cannot find extension function
SQLSRV_SQLTYPE_NVARCHAR in global function table in Unknown on line 0  
  
Warning: Internal error: Cannot find extension function
SQLSRV_SQLTYPE_VARBINARY in global function table in Unknown on line 0  
  
Warning: Internal error: Cannot find extension function SQLSRV_SQLTYPE_VARCHAR
in global function table in Unknown on line 0  
Extension [ <persistent> extension #32 sqlsrv version 1.1.428.1 ] {  

  * INI {   
Entry [ sqlsrv.WarningsReturnAsErrors <ALL> ]  
Current = '1'  
}  
Entry [ sqlsrv.LogSeverity <ALL> ]  
Current = '0'  
}  
Entry [ sqlsrv.LogSubsystems <ALL> ]  
Current = '0'  
}  
}  

  * Constants [65] {   
Constant [ integer SQLSRV_ERR_ERRORS ] { 0 }  
Constant [ integer SQLSRV_ERR_WARNINGS ] { 1 }  
...  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 16926](http://sqlsrvphp.codeplex.com/workitem/16926)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 23, 2010 at 3:05 PM
**Reported by:**	RQuadling
**Updated on:**	Jul 19, 2010 at 11:19 AM
**Updated by:**	RQuadling

**Comment by meet-bhagdev** [comment]
The latest driver does not return warnings when using the --re. We will close this unless we hear any specific issues with this.
