### ISSUE TITLE
Ubuntu/NginX: Loading ext gives undefined symbol: SQLAllocHandle

### ISSUE THREAD

**Issue by ccondrup** [Azure/msphpsql#120]
Hi there and thanks for your continued work on this!

I want to use the Laravel PHP framework to connect to SQL Server using PHP7, and I'm currently trying to get it working in the [Homestead environment](https://laravel.com/docs/5.2/homestead) - so you could quite easily recreate the VM setup I'm using for this. I'm on Homestead v0.5.0, an Ubuntu 16.04 & NginX 1.11 based VM, the host is Win10x64 using Virtualbox provider.

I'm experiencing the same error message as https://github.com/Azure/msphpsql/issues/104
`symbol lookup error: /usr/lib/php/20151012/php_pdo_sqlsrv_7_nts.so: undefined symbol: SQLAllocHandle`
(Side note: If I set extension to the thread safe module the error goes away and FPM starts successfully but still no module is loaded.)

Connecting to the SQL server using sqlcmd from the Ubuntu VM CLI (vagrant ssh) works like expected. I used the install script [installodbc_ubuntu.sh](https://github.com/Azure/msphpsql/blob/PHP-7.0-Linux/ODBC%20install%20scripts/installodbc_ubuntu.sh). 
Various output:

	Installing the Microsoft ODBC Driver 13 for SQL Server- Ubuntu                  
																					
	Microsoft ODBC Driver 13 for SQL Server Installation Script                     
	Copyright Microsoft Corp.                                                       
																					
	Starting install for Microsoft ODBC Driver 13 for SQL Server                    
																					
	Checking for 64 bit Linux compatible OS ..................................... OK
	Checking required libs are installed ........................................ OK
	unixODBC utilities (odbc_config and odbcinst) installed ..................... OK
	unixODBC Driver Manager version 2.3.1 installed ............................. OK
	unixODBC Driver Manager configuration correct .............................. OK*
	Microsoft ODBC Driver 13 for SQL Server already installed ............ INSTALLED
	Microsoft ODBC Driver 13 for SQL Server files copied ........................ OK
	Symbolic links for bcp and sqlcmd created ................................... OK
	Microsoft ODBC Driver 13 for SQL Server registered ................... INSTALLED
																					
	Install log created at /tmp/msodbcsql.3553.15855.21630/install.log.             
																					
	One or more steps may have an *. See README for more information regarding      
	these steps.                                                                    

---

	$ systemctl status php7.0-fpm.service

	● php7.0-fpm.service - The PHP 7.0 FastCGI Process Manager
	   Loaded: loaded (/lib/systemd/system/php7.0-fpm.service; enabled; vendor preset: enabled)
	   Active: failed (Result: exit-code) since Tue 2016-08-02 12:08:09 UTC; 18s ago
		 Docs: man:php-fpm7.0(8)
	  Process: 20516 ExecStart=/usr/sbin/php-fpm7.0 --nodaemonize --fpm-config /etc/php/7.0/fpm/php-fpm.conf (code=exited, status=127)
	 Main PID: 20516 (code=exited, status=127)

	 systemd[1]: Starting The PHP 7.0 FastCGI Process Manager... 
	 php-fpm7.0[20516]: /usr/sbin/php-fpm7.0: symbol lookup error: /usr/lib/php/20151012/php_pdo_sqlsrv_7_nts.so: undefined symbol: SQLAllocHandle
	 systemd[1]: php7.0-fpm.service: Main process exited, code=exited, status=127/n/a
	 systemd[1]: Failed to start The PHP 7.0 FastCGI Process Manager.
	 systemd[1]: php7.0-fpm.service: Unit entered failed state.
	 systemd[1]: php7.0-fpm.service: Failed with result 'exit-code'.
	
---
	
	$ odbcinst -q -d -n "ODBC Driver 13 for SQL Server"
	[ODBC Driver 13 for SQL Server]
	Description=Microsoft ODBC Driver 13 for SQL Server
	Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
	Threading=1
	UsageCount=4

---

	 PHP Version 7.0.9-1+deb.sury.org~xenial+1
	 Linux homestead 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 
	
	$ cat /etc/php/7.0/mods-available/pdo_sqlsrv.ini
	extension=php_pdo_sqlsrv_7_nts.so

I hope this is sufficient info to look into it, I'm on thin ice here. Just bear with me and ask away.	
For instance I'm not entirely sure whether I should leave php extensions odbc and pdo_odbc enabled or not? Is any form of odbc required as a base, or are those just leftovers from me trying php-odbc from the package manager?
Thanks.

**Comment by xalopp** [comment]
On my  [Ubuntu 16.04 Testing VM](https://github.com/xalopp/vagrant-php7sqlsrv) running `PHP 7.0.9-1+deb.sury.org~xenial+1 (cli)`,  `pdo_odbc` must be enabled, otherwise I get the error message `undefined symbol: SQLAllocHandle`:

```
ubuntu@ubuntu-xenial:~$ php /vagrant/tests/pdo_connection.php

PDO sqlsrv driver available: yes
PDO sqlsrv connection successfull: yes
ubuntu@ubuntu-xenial:~$ sudo phpdismod pdo_odbc
ubuntu@ubuntu-xenial:~$ php /vagrant/tests/pdo_connection.php 
php: symbol lookup error: /usr/lib/php/20151012/pdo_sqlsrv.so: undefined symbol: SQLAllocHandle
```

My recommendation is to keep `php7.0-odbcphp7.0-odbc` installed, and the PHP extension `odbc` and `pdo_odbc` enabled.

**Comment by neoxium** [comment]
Hi, I got the same error at loading pdo_sqlsrv_nts extension (undefined symbol : SQLAllocHandle), environment and outputs are very similar to those of @ccondrup although I don't have any webserver installed (just php7.0 CLI and FPM).

Extensions odbc and pdo_odbc are enabled.

**Comment by xalopp** [comment]
I've created a puppetized Vagrant Box https://github.com/xalopp/vagrant-php7sqlsrv which my setup.
In this box, sqlsrv and pdo_sqlsrv are working "properly".

Can you check, if your dynamic linker is properly configured?

SQLAllocHandle is provided by /usr/local/lib/libodbc.so.2 which was installed by the script `ODBC install scripts/installodbc_ubuntu.sh` .
```
nm /usr/local/lib/libodbc.so.2 | grep SQLAllocHandle
0000000000007e90 T SQLAllocHandle
0000000000006cb0 t __SQLAllocHandle
0000000000007ea0 T SQLAllocHandleStd
```
The liker is configured to look for libraries in `/usr/local/lib`:

```
$ cat /etc/ld.so.conf.d/libc.conf 
# libc default configuration
/usr/local/lib
$ ldconfig -p | grep /usr/local/lib
	libodbcinst.so.2 (libc6,x86-64) => /usr/local/lib/libodbcinst.so.2
	libodbcinst.so (libc6,x86-64) => /usr/local/lib/libodbcinst.so
	libodbccr.so.2 (libc6,x86-64) => /usr/local/lib/libodbccr.so.2
	libodbccr.so (libc6,x86-64) => /usr/local/lib/libodbccr.so
	libodbc.so.2 (libc6,x86-64) => /usr/local/lib/libodbc.so.2
	libodbc.so (libc6,x86-64) => /usr/local/lib/libodbc.so
```

**Comment by meet-bhagdev** [comment]
@xalopp I wil verify if the dynamic linker is properly configured and get back to you soon.

**Comment by ccondrup** [comment]
Sort of fixed now! @xalopp thanks! I went through other issues reported lately and saw [PR 126](https://github.com/Azure/msphpsql/pull/126) about install script. I re-ran this new version of the installer, then used the commands [mentioned here](https://github.com/Azure/msphpsql/issues/124#issuecomment-237827659) to get the mods enabled.

    $ sudo service php7.0-fpm restart
    $ php -m | grep _sql
    pdo_sqlite
    pdo_sqlsrv

Boom, now I had pdo_sqlsrv in both cli and phpinfo(), nice! Running test-script:
```php
<?php
$conn = false;
$db = 'mydb';
$host = '192.168.1.121';
$user = 'myuser';
$pass = 'mypw';

$table = "[mydb].[prefix].[Customers]";
$sqlwhere = "CustomerNo=11926";

try {
	$conn = new PDO("sqlsrv:server=$host;database=$db", $user, $pass);
	$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

	$prep = $conn->prepare("SELECT Name FROM $table WHERE $sqlwhere");
	$prep->execute();
	
	$arr = $prep->fetchAll();
	print_r($arr);

} catch(PDOException $e) {
	echo 'ERROR: ' . $e->getMessage();
}
```
This script now works every 3rd time I refresh. Result is:

	Refresh, get: Array ( [Name] => John Doe [0] => John Doe )
	Refresh, get: Warning: Uncaught PDOException: Invalid handle returned. Fatal error: Invalid handle returned. 
	Refresh, get: Warning: Uncaught PDOException: Invalid handle returned. Fatal error: Invalid handle returned. 
	Refresh, get: Array ( [Name] => John Doe [0] => John Doe )
	Refresh, get: Warning: Uncaught PDOException: Invalid handle returned. Fatal error: Invalid handle returned. 
    ... and so on, every 3 tries works.

Exception occurs on line 13 is where new PDO() is invoked. Should this be reported in a separate issue?

**Comment by meet-bhagdev** [comment]
@ccondrup Yep, please open a new issue for this and we will look into it :)

**Comment by ccondrup** [comment]
After reinstalling php7.0-odbc and re-enabling odbc and pdo_odbc the output result is now consistent and I consider this issue fixed. Thanks! Commands used, may be of use to some:
```bash
sudo service php7.0-fpm stop
sudo apt-get install php7.0-odbc
sudo phpenmod pdo_odbc
sudo service php7.0-fpm start
php -m  | grep odbc
php -i | grep odbc
```
Now encountering a new problem as reported in #129
