### ISSUE TITLE
Reproducible PHP process crash

### ISSUE THREAD

**Issue by david-garcia-garcia** [Azure/msphpsql#121]
Yesterday I closed Issue:

https://github.com/Azure/msphpsql/issues/63

because the repro script there worked as expected. 

I soon found out that the same problem still happens on other scenarios, but it needed a new repro script as the original one had been fixed.

While building the repro script, I managed to build a script that crashes PHP.

See the script here:

http://pastebin.com/VENbce75

This is PHP 7.0.9 x64 on Windows with sqlsrv 4.1.0.0

This is the crash detail from the system event viewer:

Faulting application name: php-cgi.exe, version: 7.0.9.0, time stamp: 0x578fb9d9
Faulting module name: php7.dll, version: 7.0.9.0, time stamp: 0x578fc24b
Exception code: 0xc0000005
Fault offset: 0x00000000001f726a
Faulting process id: 0x3aa0
Faulting application start time: 0x01d1ed52c8dd0d3a
Faulting application path: D:\php_runtime\php764\php-cgi.exe
Faulting module path: D:\php_runtime\php764\php7.dll
Report Id: d4234854-d6ef-487f-b301-db4ecd4f9872
Faulting package full name: 
Faulting package-relative application ID: 

If I comment out the followin line from the repro script:

$pdo_options[PDO::ATTR_EMULATE_PREPARES] = TRUE;

then the crash goes away (there are other errors, but the focus of this post is the crash itself).

**Comment by Rvdv87** [comment]
Having the same problem here, when disable ATTR_EMULATE_PREPARES the crash goes away.

**Comment by meet-bhagdev** [comment]
@david-garcia-garcia thanks for the repro script. Let us emulate it and understand what is causing the crash. We will keep you posted.

**Comment by meet-bhagdev** [comment]
@david-garcia-garcia @Rvdv87 : We believe we closed this issue with our latest release https://github.com/Azure/msphpsql/releases. Can you help us validate?

**Comment by david-garcia-garcia** [comment]
Fixed! Thanks, now I can go back to the original issue.
