### ISSUE TITLE
Inconsistent behavior with Emulate Prepares

### ISSUE THREAD

**Issue by david-garcia-garcia** [Azure/msphpsql#122]
Repro script:

http://pastebin.com/CWHAi74z

Current output:

SQLSTATE[HY093]: Invalid parameter number: parameter was not defined
NO EXCEPTION?

Expected output:

SQLSTATE[HY093]: Invalid parameter number: parameter was not defined
SQLSTATE[HY093]: Invalid parameter number: parameter was not defined

**Comment by david-garcia-garcia** [comment]
This is the right script:

http://pastebin.com/fDgrsy7d

**Comment by meet-bhagdev** [comment]
@david-garcia-garcia: We believe we closed this issue with our latest release https://github.com/Azure/msphpsql/releases. Can you help us validate?

**Comment by david-garcia-garcia** [comment]
This is not fixed. The script still outputs:

> SQLSTATE[HY093]: Invalid parameter number: parameter was not defined
> NO EXCEPTION?

When it should output:

> SQLSTATE[HY093]: Invalid parameter number: parameter was not defined
> SQLSTATE[HY093]: Invalid parameter number: parameter was not defined
