### ISSUE TITLE
No Connection attempt seen

### ISSUE THREAD

**Issue by LarnuUK** [Azure/msphpsql#123]
I've successfully managed to get the sqlsrv library installed on Ubuntu Server 16.04.1, however, all my connection attempts fail.

I have checked the SQL Server logs, and I cannot see any failed connection attempts from the user I am using to try and connect, or any attempt from the IP of the php server. The firewall also permits traffic from the server to the SQL Server, but we can't see any packets being submitted from it to the SQL server on port 1433 (TELNET works though).

I'm sceptical that the sqlsrv_connect is actually trying, as the php page loads instantly, I'd expect some load time or delay is the connection was being refused. 

Has anyone else had this issue and resolved?

**Comment by LarnuUK** [comment]
I have since resolved this, it appears that the Ubuntu ODBC installer script did not correctly install the ODBC drivers. I ran this manually and resolved the issue.

**Comment by meet-bhagdev** [comment]
awesome! @LarnuUK do you have any feedback on how we can improve the script? I will close the issue for now. Feel free to reopen it if you have further questions.
