### ISSUE TITLE
Ubuntu ODBC installer not compatible for unattended install

### ISSUE THREAD

**Issue by xalopp** [Azure/msphpsql#125]
[installodbc_ubuntu.sh](https://github.com/Azure/msphpsql/blob/PHP-7.0-Linux/ODBC%20install%20scripts/installodbc_ubuntu.sh) isn't working properly for unattended installation 😞 !

This can be easy reproduced on and plain vanilla Ubuntu system by calling
```
installodbc_ubuntu.sh  < /dev/null
```

This causes `apt-get install` not to install the required packages, resulting in a incomplete installation.

This can be easily be adding the `-y` option to `apt-get install`.

PR is in progress.

**Comment by meet-bhagdev** [comment]
I have accepted your PR (thank you 👍 :) ). I will close this issue. Feel free to re-open this if you have any questions.
