### ISSUE TITLE
MSSQL column types 'image' & 'text' gives Invalid sql_display_size

### ISSUE THREAD

**Issue by ccondrup** [Azure/msphpsql#129]
After fixing #120 I have [Homestead](https://laravel.com/docs/5.2/homestead) 0.5.0 running with NginX 1.11 and PHP 7 on Ubuntu 16.04 using the MS ODBC driver 13. Querying the MSSQL server from PHP with the sqlsrv driver works:
```sql
SELECT [Name] FROM Customers WHERE Id=123
> Array( [Name] => "John Doe")
```

However, using `SELECT *` results in
`Fatal error: Invalid sql_display_size` on the line `$prep->fetchAll()`:
```php
<?php
	$pdo = new PDO("sqlsrv:server=$host;database=$db", $user, $pass);
	$prep = $pdo->prepare("SELECT * FROM Customers WHERE Id=123");
	$prep->execute();
	print_r( $prep->fetchAll() );
```

[This comment](https://github.com/Azure/msphpsql/issues/104#issuecomment-230678385) suggests to cast the type in the select, but I want to use the Laravel framework where its ORM ([Eloquent](https://laravel.com/docs/5.2/eloquent)) is building the queries for me.

Info: [This stackoverflow Q](http://stackoverflow.com/questions/36469538/pdo-mssql-fatal-error-invalid-sql-display-size-in) seems to be identical but on a Windows server.

**Comment by david-garcia-garcia** [comment]
The PDO driver has historically chocked on types that have no explicit map inside the PDO driver. Things such as variants...

I'd rather the driver brought back this data into PHP in a best-effort approach in a string format, instead of throwing an exception.

It will be helpful to know the schema of the table Customers, probably the type of one of the columns does not have a PHP match.

**Comment by ccondrup** [comment]
Thanks! Here's the schema https://gist.github.com/ccondrup/3545ba1c1c747c5502a389de528567cb
It's from a 3rd party, and I cannot change it as other systems depend on this schema. Included FKs just to show there are quite a few.

**Comment by david-garcia-garcia** [comment]
Text type columns throw errors? That is very bad news. I could expect that from image (which by the way could be treated just as a varbinary column instead of crashing).

**Comment by meet-bhagdev** [comment]
@david-garcia-garcia @ccondrup : We believe we closed this issue with our latest release https://github.com/Azure/msphpsql/releases. Can you help us validate?

**Comment by ccondrup** [comment]
Very good news!

After updating to "release 4.0.3":
- phpinfo() now gives me pdo_sqlsrv "ExtensionVer 	4.0.8822.0 "
- querying both text & image columns works as expected

Solved, thanks!

**Comment by meet-bhagdev** [comment]
@ccondrup Glad that this worked out. Let me know if you have any more questions.
