### ISSUE TITLE
Linux X64 - PHP Fatal error:  sqlsrv_connect: Unknown exception caught.

### ISSUE THREAD

**Issue by vinise** [Azure/msphpsql#131]
Hi,

I get a fatal error trying to open a connection on a X64 linux PHP 7.0.9-1 ( NTS )
        $options = array("Database"=>"database", "Uid"=>"sa", "PWD"=>"password");
        $conn = sqlsrv_connect("server", $options); 

all drivers seems to be installed :

odbcinst –j` `odbcinst -q -d -n "ODBC Driver 13 for SQL Server"
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
Threading=1
UsageCount=1   

phpinfo ==> sqlsrv ==> ExtensionVer	4.0.2.0

Any idea where that could come from?

Thanks for your help

**Comment by meet-bhagdev** [comment]
@vinise Can you confirm if you can connect via sqlcmd? `sqlcmd -S <myserver> -d <mydatabase> -U <myusername> -P <mypassword> -I`

**Comment by vinise** [comment]
THANKS men this command showed me a problem of Locales
So reconfigured the locales and it works like a charm now !!! :smile: 

You should add that on LinuxTutorial file as check ;)

Thanks again
