### ISSUE TITLE
installodbc_redhat.sh: line 57: cd: usr/lib64: No such file or directory

### ISSUE THREAD

**Issue by super-vip** [Azure/msphpsql#132]
@meet-bhagdev

File: installodbc_redhat.sh

The fifty-seventh line "CD usr/lib64" is needed? Or is there an error in the command?

error:
installodbc_redhat.sh: line 57: cd: usr/lib64: No such file or directory

**Comment by meet-bhagdev** [comment]
Fixed! Can you give the script a shot and let me know how its going?
