### ISSUE TITLE
Source for Linux

### ISSUE THREAD

**Issue by szepeviktor** [Azure/msphpsql#136]
Where is the PHP 7 source for Linux available?

**Comment by MCF** [comment]
https://github.com/Azure/msphpsql/tree/PHP-7.0-Linux

**Comment by szepeviktor** [comment]
Thank you.
It seems to me only the binaries are there.

**Comment by meet-bhagdev** [comment]
Uploaded now.  :+1:

**Comment by szepeviktor** [comment]
Thank you.
