### ISSUE TITLE
Add required header to config.w32

### ISSUE THREAD

**Issue by v-mabarw** [Azure/msphpsql#20]
Hi.  
  
Adding the line ...  

    
    
       CHECK_HEADER_ADD_INCLUDE('sqlncli.h', 'CFLAGS_SQLSRV_ODBC');
    

to config.w32 would be useful for new builds.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 19302](http://sqlsrvphp.codeplex.com/workitem/19302)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Dec 14, 2010 at 4:57 PM
**Reported by:**	RQuadling
**Updated on:**	Dec 14, 2010 at 4:57 PM
**Updated by:**	RQuadling

**Comment by meet-bhagdev** [comment]
The PHP Driver uses the Microsoft ODBC Driver and not the SQL Server Native Client. We have updated our header files and thus are marking this issue closed.
