### ISSUE TITLE
PHP 5.5 & VC11 Support

### ISSUE THREAD

**Issue by v-mabarw** [Azure/msphpsql#33]
The current version 3.0.1 does not support use with the newly released PHP 5.5
binaries for Windows. The new version of PHP is now compiled against VC11
instead of the previous VC10 and the code contains conflicts with the new
version as documented in this comment.  
  
[ http://sqlsrvphp.codeplex.com/discussions/441706
](http://sqlsrvphp.codeplex.com/discussions/441706)  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 22422](http://sqlsrvphp.codeplex.com/workitem/22422)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jul 25, 2013 at 1:03 PM
**Reported by:**	brentil
**Updated on:**	Jul 13 at 10:31 AM
**Updated by:**	VahaC

**Comment by SumoLion** [comment]
The latest release of the Microsoft Drivers 3.1 for PHP for SQL Server now supports PHP 5.5 and VC11.
