### ISSUE TITLE
PHP 5.6 Support

### ISSUE THREAD

**Issue by mlhkr** [Azure/msphpsql#42]
When do you plan to release binaries for PHP 5.6?
Current PHP version is 5.6.4 and latest supported version by sql driver is 5.5.

Thanks

**Comment by Lfsantos** [comment]
We are working on it, but I cannot  comment on dates right now.

Thanks

**Comment by deancsmith** [comment]
+1

**Comment by Lfsantos** [comment]
We are working on it.  I cannot comment on dates yet, but will do as soon as the schedule were finalized.

Thanks
________________________________

**Comment by HNygard** [comment]
+1

**Comment by jbeall** [comment]
Looking forward to this... hopefully we'll see this before PHP 7 is released.

**Comment by arhakal** [comment]
+1

**Comment by rwitchell** [comment]
+1 to this, Luiz. Also thanks for your hard work on this, and keeping active and replying on Github :) .

**Comment by zeroedin-bill** [comment]
+1

**Comment by Jan-E** [comment]
@Lfsantos What is keeping you? https://github.com/Azure/msphpsql/pull/44/commits

**Comment by Lfsantos** [comment]
Just saw your message.  Just sent it to my Dev team.

Thanks for pointing out and fixing it.

Sent from my iPad

On Mar 8, 2015, at 1:01 PM, Jan-E <notifications@github.com<mailto:notifications@github.com>> wrote:


@Lfsantos<https://github.com/Lfsantos> What is keeping you? https://github.com/Azure/msphpsql/pull/44/commits

-

**Comment by tradetzki** [comment]
Any news about 5.6 support?
We are currently planning to move from php 5.4 directly to 5.6 without spending additional effort in 5.5.

Just a rough timeframe would help us to decide wether we have to do it in two steps (5.4->5.5->5.6) or one step is enough (5.4->5.6).

Thanks in advance.

**Comment by Lfsantos** [comment]
Hi,

We just released support for 5.6 for Windows today ☺

Thanks

**Comment by zeroedin-bill** [comment]
Kudos :)

**Comment by tradetzki** [comment]
Great news. Thanks and congratulations. 
Thumbs up!!!!
W'll check it right tomorrow.

:+1:

**Comment by mlhkr** [comment]
Congratulations :)

**Comment by david-garcia-garcia** [comment]
The binaries are already available here:

http://www.microsoft.com/en-us/download/details.aspx?id=20098

**Comment by SumoLion** [comment]
5.6 binaries released as linked in comments and in README
