### ISSUE TITLE
Download link is impossible to find

### ISSUE THREAD

**Issue by david-garcia-garcia** [Azure/msphpsql#53]
The download link for the binaries of this driver is not in the Readme file or anywhere easy to find.

Anyone reaching this project will have a tough time finding where the binaries are.

http://www.microsoft.com/en-us/download/details.aspx?id=20098

Another option is to provide a binary download directly from github.

**Comment by meet-bhagdev** [comment]
Thanks for the issue david.
The link can be found on azure and our team blog.
Azure : http://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-php-simple-windows/
MSDN Blog : http://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-php-simple-windows/

We will add the link to the Readme.
Hope this helps.
