### ISSUE TITLE
Download not occuring

### ISSUE THREAD

**Issue by srph** [Azure/msphpsql#55]
Not sure if this is the right place to report this issue. Downloading the binary files over the [Download Center](https://www.microsoft.com/en-us/download/confirmation.aspx?id=20098) doesn't work; it seems that there are url scheme errors.

This is what I get in the console everytime I start the download:

```
Mixed Content: The page at 'https://www.microsoft.com/en-us/download/confirmation.aspx?id=20098' was loaded over HTTPS, but requested an insecure resource 'http://download.microsoft.com/download/C/D/B/CDB0A3BB-600E-42ED-8D5E-E4630C905371/SQLSRV30.EXE'. This request has been blocked; the content must be served over HTTPS.
script.jsx?k=6848d512-e14d-4e09-1194-5de6bc24cbe6_f3c4a4eb-d525-0def-8753-f4835e2f9949_8c693876-7ed…:1 Resource interpreted as Document but transferred with MIME type image/gif: "https://c1.microsoft.com/c.gif?DI=4050&did=1&t=".MscomGetMUID @ script.jsx?k=6848d512-e14d-4e09-1194-5de6bc24cbe6_f3c4a4eb-d525-0def-8753-f4835e2f9949_8c693876-7ed…:1MscomInit @ script.jsx?k=6848d512-e14d-4e09-1194-5de6bc24cbe6_f3c4a4eb-d525-0def-8753-f4835e2f9949_8c693876-7ed…:1(anonymous function) @ script.jsx?k=6848d512-e14d-4e09-1194-5de6bc24cbe6_f3c4a4eb-d525-0def-8753-f4835e2f9949_8c693876-7ed…:1
confirmation.aspx?id=20098:1 Mixed Content: The page at 'https://www.microsoft.com/en-us/download/confirmation.aspx?id=20098' was loaded over HTTPS, but requested an insecure resource 'http://download.microsoft.com/download/C/D/B/CDB0A3BB-600E-42ED-8D5E-E4630C905371/SQLSRV30.EXE'. This request has been blocked; the content must be served over HTTPS.
confirmation.aspx?id=20098:1 Mixed Content: The page at 'https://www.microsoft.com/en-us/download/confirmation.aspx?id=20098' was loaded over HTTPS, but requested an insecure resource 'http://download.microsoft.com/download/C/D/B/CDB0A3BB-600E-42ED-8D5E-E4630C905371/SQLSRV20.EXE'. This request has been blocked; the content must be served over HTTPS.
confirmation.aspx?id=20098:1 Mixed Content: The page at 'https://www.microsoft.com/en-us/download/confirmation.aspx?id=20098' was loaded over HTTPS, but requested an insecure resource 'http://download.microsoft.com/download/C/D/B/CDB0A3BB-600E-42ED-8D5E-E4630C905371/SQLSRV31.EXE'. This request has been blocked; the content must be served over HTTPS.
confirmation.aspx?id=20098:1 Mixed Content: The page at 'https://www.microsoft.com/en-us/download/confirmation.aspx?id=20098' was loaded over HTTPS, but requested an insecure resource 'http://download.microsoft.com/download/C/D/B/CDB0A3BB-600E-42ED-8D5E-E4630C905371/SQLSRV32.EXE'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by travy** [comment]
There is a trick I've found to get it to download.  After going to the download page (https://www.microsoft.com/en-us/download/details.aspx?id=20098), selecting the package you want and clicking next you will see a link that says click here if the package does not download in 30 seconds.  Click on that link and you will see an option for direct download.  That link is working as of 6-21-2015 to get the package to download.  Hopefully Microsoft will make this work correctly in the future.  It is worth noting by the way that this is 32-bit only.  I have yet to find a 64-bit version.

![php5_5](https://cloud.githubusercontent.com/assets/4945102/8274308/3a1745bc-185d-11e5-872d-009804392789.PNG)

**Comment by meet-bhagdev** [comment]
Thanks for the answer travy. I am a Program Manager on the Azure SQL DB team working on client drivers. I was wondering if you can hare some of your pain points regarding the 32bit only version. Have you had any difficulty making it work on your 64 bit machine?
Best,
Meet Bhagdev
Program Manager, Microsoft

**Comment by travy** [comment]
Hello Bhagdev,

Yea the problem with the 32-bit version is that it is incompatible with 64-bit PHP.  I've attached a copy of my error log for PHP v5.6.6 NTS.  I do have a custom built 64 bit driver that I had built myself a year ago but I was hoping to transition to the official driver now that it is out.  I maintain a large PHP based application for my company which contains a lot of binary manipulation operations which is why I would be unable to transition to a 32-bit PHP environment easily.


![log](https://cloud.githubusercontent.com/assets/4945102/8321259/9bbacf00-19f2-11e5-8905-b0e9df3ec324.PNG)

**Comment by meet-bhagdev** [comment]
Hi Travy,
Thanks for the reply. Can I know what does your dev environment look like?
We have a video and a blog post that can help you connect to Azure SQL DB/SQL Server on our machine using PHP from our driver.
You should check them out and see if they apply to you : 
https://www.youtube.com/watch?v=0oCjiRK_tUk
http://blogs.msdn.com/b/sqlphp/archive/2015/05/11/getting-started-with-php-and-microsoft-sql-server.aspx

**Comment by meet-bhagdev** [comment]
Hello @travy 
I am closing this issue. Please let me know if you still have trouble with this and I will re open it and try to help you.
Best,
Meet

**Comment by srph** [comment]
@travy's solution had this fixed for me months ago. Closing this.
