### ISSUE TITLE
PDO_SQLSRV lastInsertId method does not support sequences.

### ISSUE THREAD

**Issue by zeroedin-bill** [Azure/msphpsql#64]
When a sequence is created in a SQL Server 2012 (or greater version) database, calling ```$pdo->lastInsertId($sequenceName);``` should return the current value of the sequence.

Instead, it returns an empty string, ```''```

Please refer to [this unit test](https://github.com/doctrine/dbal/blob/master/tests/Doctrine/Tests/DBAL/Functional/WriteTest.php#L150-L174) in the [Doctrine DBAL](https://github.com/doctrine/dbal) functional testsuite.

The test currently fails on SQL Server 2012. Later versions were not tested.

**Comment by meet-bhagdev** [comment]
Thanks for reporting it @zeroedin-bill 
I am forwarding this issue to our developer team. Please stay tuned for updates. If you could share with code that would help us reproduce your issue, it would much appreciated.

Best,
Neet

**Comment by zeroedin-bill** [comment]
@meet-bhagdev here you go:

```php
$host = "localhost";
$dbname = "dbname";
$username = "user";
$password = "password";
$dsn = "sqlsrv:Server=$host;Database=$dbname";
$db = new PDO($dsn, $username, $password);
$db->exec("CREATE SEQUENCE test_seq START WITH 1 INCREMENT BY 1 MINVALUE 1");
$nextValue = $db->query("SELECT NEXT VALUE FOR test_seq")->fetchColumn();
$lastInsertId = $db->lastInsertId('test_seq');

echo "Sequence returned: '$nextValue', lastInsertId returned '$lastInsertId'.";
```

Outputs:
```
Sequence returned: '1', lastInsertId returned ''.
```

**Comment by zeroedin-bill** [comment]
The [PDO documentation](http://php.net/manual/en/pdo.lastinsertid.php) for this function specifies that support is contingent on the underlying driver supporting sequences, but given that SQL Server 2012 does support sequences, and this is the proper way to get the last value returned by a sequence, this should be supported at the driver level.

**Comment by meet-bhagdev** [comment]
Issue has been sent to the developers who have been working on this driver. Stay tuned for updates.

**Comment by meet-bhagdev** [comment]
Hi @zeroedin-bill 
We were able to reproduce this, we are currently examining what is causing the issue so stay tuned.
Thanks,
Meet

**Comment by zeroedin-bill** [comment]
@meet-bhagdev :+1:

**Comment by meet-bhagdev** [comment]
Hi @zeroedin-bill 

We have determined what is causing the issue. The driver is not supporting the 2nd use case of the lastInsertId function, namely the ability to pass a sequence object name to this function and get the next value. Unfortunately there isn't a quick fix or a workaround at this time. Our engineers are aware of the problem and will try to include it in the upcoming coding sprints. 

Thanks a lot for letting us know about this.
