### ISSUE TITLE
String or binary data would be truncated

### ISSUE THREAD

**Issue by sirio3mil** [Azure/msphpsql#73]
Im getting this errors in some fields: [Microsoft][SQL Server Native Client 11.0][SQL Server]String or binary data would be truncated.

Problem is that I know wicth column is supposed affected, but column have enougth character length.

Text length = 391 characters
Column character length = 400 (varchar)

If I execute same query on SSMS I get succesfull result.

I'm using PHP 5.5. What would be the problem? 

Regards.

**Comment by tschallacka** [comment]
check your text encoding that you shove into it...

Try 

    SELECT LEN(:?) as stringlength  

as query to see how big your string is according to sql server
