### ISSUE TITLE
Driver crashes when using prepared statement from subclass

### ISSUE THREAD

**Issue by theodorejb** [Azure/msphpsql#74]
Thanks for releasing the Early Technical Preview for PHP 7! I tried out the Non Thread Safe version on PHP 7.0.2, but unfortunately it's crashing when I try to use a prepared statement from a subclass. Strangely, the crash doesn't occur if I don't call the parent constructor, or if I comment out the `throw new Exception` lines.

This is based on real-world code in the [PeachySQL](https://github.com/theodorejb/peachy-sql) library.

```php
<?php

$connection = sqlsrv_connect('Computer-Name\SQLEXPRESS', ['Database' => 'MyDatabase']);

$sql = "UPDATE Users SET name = ? WHERE user_id = ?";
$id = $name = null;
$stmt = new Statement(sqlsrv_prepare($connection, $sql, [&$name, &$id]));

$names = [
    1 => 'Michael J. Fox',
    2 => 'Christopher A. Lloyd',
];

foreach ($names as $id => $name) {
    $stmt->execute();
}

$stmt->close();

class BaseStatement
{
    public function __construct() {}
}

class Statement extends BaseStatement
{
    private $stmt;

    public function __construct($stmt)
    {
        parent::__construct(); // neither execute() nor close() cause a crash if I comment out this line
        $this->stmt = $stmt;
    }

    public function execute()
    {
        if (!sqlsrv_execute($this->stmt)) {
            // calling execute() causes crash unless I comment out the below line
            throw new Exception('Failed to execute statement: ' . print_r(sqlsrv_errors(), true));
        }
    }

    public function close()
    {
        if (!sqlsrv_free_stmt($this->stmt)) {
            // calling close() causes crash unless I comment out the below line
            throw new Exception('Failed to close statement: ' . print_r(sqlsrv_errors(), true));
        }
    }
}
```

**Comment by nickmccally** [comment]
What type of crashing were you experiencing? I am having issues with sqlsrv_query only with specific queries. I get the following error message: C:\Program Files (x86)\PHP\v7.0\php-cgi.exe - The FastCGI process exited unexpectedly

My issue is NTS too, so I am thinking these may be related.

**Comment by theodorejb** [comment]
I'm running the above code in a `test.php` file from the command line, and it crashes with a "CLI has stopped working" message:
![cli has stopped working](https://cloud.githubusercontent.com/assets/3053271/12739815/8cf5d1c8-c932-11e5-8870-046e539f205d.PNG)

**Comment by nickmccally** [comment]
@theodorejb - this has been absolute madness for me. Spent 6-7 hours trying to figure out what was causing it, because SOME queries worked. 

I reinstalled from php scratch 3 times. If you are using php 7 from IIS web installer x86 I have the fix. (Fyi I even went the long route and did a manual install at one point, which was failing too) 

The download checks to make sure you have the visual c++ runtime 2012 for x86. I did. I reinstalled this package over 7 times today, including other versions. I read numerous posts about this resolving it for others to no available for me. Finally I did the opposite. 

You need to uninstall Visual C++ runtime 2012 and reinstall x64 .. That's right, x64 for x86 php. Every single query works, without a single crash at this point. I was getting an insane about of 500 errors before, and they were very inconsistent. Sometimes the same query worked, and upon refresh I'd get a 500. 

Here is the link: https://www.microsoft.com/en-us/download/details.aspx?id=30679

Not sure if this is something we can say is specific to this driver or if it's the php.net team-- because they've been compiling in x64. Real strange.

**Comment by meet-bhagdev** [comment]
@nickmccally : thanks for the update. This is not idea behaviour. We will investigate this and let you know when we have something to share. 
@theodorejb : Does @nickmccally's hack solve your issue for now?

**Comment by theodorejb** [comment]
@meet-bhagdev No, I tried uninstalling all the Visual C++ runtimes on my PC and reinstalling the version @nickmccally linked, but the crash is still occurring.

**Comment by meet-bhagdev** [comment]
@theodorejb: Where did you get the PHP 7 for IIS from? Did you get it from the WebPI (https://www.microsoft.com/web/downloads/platform.aspx)?

**Comment by theodorejb** [comment]
@meet-bhagdev No, I downloaded it from http://windows.php.net/downloads/releases/php-7.0.2-nts-Win32-VC14-x86.zip. Unzipped in C:\php and added the directory to path.

**Comment by theodorejb** [comment]
Before testing my above script, create a `Users` table like this:

```sql
CREATE TABLE Users (
    user_id int IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL
)

INSERT INTO Users (name)
VALUES ('Martin'), ('Emmett')
```

If the script runs successfully, it should update "Martin" to "Michael J. Fox" and "Emmett" to "Christopher A. Lloyd." However, for me it crashes PHP unless I comment out the `parent::__construct()` call or `throw new Exception` lines.

**Comment by nickmccally** [comment]
@theodorejb The version I linked has an option to select type. Did you select x64 on the type to download? The x84 and x64 download names were the same. (I played with these quite a bit and redownloaded several times)

**Comment by theodorejb** [comment]
@nickmccally Yes, I selected the x64 version, but it didn't fix the crash. Have you tried running the above script yourself to see if you can reproduce it?

**Comment by theodorejb** [comment]
This crash is still occurring with today's driver update on PHP 7.0.3.

**Comment by meet-bhagdev** [comment]
@theodorejb We are aware of this and will aim to fix it. Will share an update once we have concluded our investigation and have a fix.

**Comment by meet-bhagdev** [comment]
Closing this as the #4.0.2 release fixed this issue of the driver crashing while using the script above.
