### ISSUE TITLE
PHP7 wrong resource type close connection

### ISSUE THREAD

**Issue by sirio3mil** [Azure/msphpsql#77]
I have a correct query (works on SSMS) then I execute without any error with sqlsrv_query and get a resourse type (get_resource_type) SQL Server Statement but when I run sqlsrv_fetch_array I get this error Warning: sqlsrv_fetch_array(): supplied resource is not a valid ss_sqlsrv_stmt resource.

After that error I execute sqlsrv_free_stmt whit same error and after that I lost my db connection.

Im using your last driver version NTS, PHP 7.0.4RC1 and Visual C++ 2015 x86.

Many others queries works fine.

**Comment by meet-bhagdev** [comment]
@sirio3mil do you have a repro script that you can share? 
Thanks,
Meet

**Comment by sirio3mil** [comment]
I'm testing (finally) php 7.0.7 x64 with last driver version 4.0.4 and it look like fixed. Regards.

**Comment by meet-bhagdev** [comment]
Awesome! I will go ahead and close this issue :+1:
