### ISSUE TITLE
sqlsrv_fetch_array: you have to define fetchType or else php crashes

### ISSUE THREAD

**Issue by meet-bhagdev** [Azure/msphpsql#79]

**Comment by meet-bhagdev** [comment]
@PakL I have created a new issue for better tracking.

We tried your repro script but were not able to repro the issue. Can you share what data types are you using? What build are you using (e.g. 32 or 64, debug or release if you built it yourself).

**Comment by PakL** [comment]
I gathered all information that might be of use for you:

The database table I tested with runs on a _SQL Server 10.50.4339 (64bit)_ and has the following data types:
```
CREATE TABLE [dbo].[table](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[bi] [bigint] NULL,
	[vc] [varchar](25) NULL,
	[dt] [datetime] NULL,
	[si] [smallint] NULL,
	[bvc] [varchar](50) NULL,
	[lt] [varchar](255) NULL,
	[ti] [tinyint] NULL,
	[fl] [float] NULL,
	CONSTRAINT [PK_table_id] PRIMARY KEY NONCLUSTERED ( [id] ASC )
	WITH (
		PAD_INDEX  = OFF,
		STATISTICS_NORECOMPUTE  = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS  = ON,
		ALLOW_PAGE_LOCKS  = ON
	) ON [PRIMARY]
) ON [PRIMARY]
```
The systems I tested on are Windows 7 and Windows Server 2008, both 64bit with PHP 7.0.4 NTS with your pre-build 64bit SQLSRV driver extension ([v4.0.2](https://github.com/Azure/msphpsql/releases/tag/v4.0.2)).

I hope this helps.

**Comment by meet-bhagdev** [comment]
@PakL we have attempted to fix this issue with the v4.0.3 release, can you help us validate?

**Comment by PakL** [comment]
@meet-bhagdev I can validate; no more crashes with 4.0.3.

**Comment by meet-bhagdev** [comment]
Glad to hear. I will close this issue then.
