### ISSUE TITLE
sqlsrv_free_stmt no longer sets stmt to null

### ISSUE THREAD

**Issue by theodorejb** [Azure/msphpsql#84]
I'm not sure if this is a bug or not, but it is a difference from the PHP 5.6 driver which I thought should be brought to your attention.

Compare running the following code in PHP 5.6 and PHP 7:

```php
$connection = sqlsrv_connect('Computer-Name\SQLEXPRESS', ['Database' => 'MyDatabase']);
$sql = "SELECT 'result' AS test";

$stmt = sqlsrv_query($connection, $sql);
$row = sqlsrv_fetch_array($stmt, SQLSRV_FETCH_ASSOC);
sqlsrv_free_stmt($stmt);

var_dump($row['test'], $stmt);
```

In PHP 5.6 the output is:
```
string(6) "result"
NULL
```

With the PHP 7 driver, it outputs:

```
string(6) "result"
resource(5) of type (Unknown)
```

This broke some of my code which assumed that `$stmt` would be null if it is closed. I was able to fix my code by manually setting `$stmt` to null after freeing the statement, so feel free to close this issue if the new behavior is intended.

**Comment by meet-bhagdev** [comment]
Hi Theodore, this is expected behavior. We will document such changes clearly to avoid confusion. Instead of checking for null I recommend you use [is_resource](http://php.net/manual/en/function.is-resource.php). Statements are resources, and that function will indicate false if the resource has been closed.
 
Cheers,
Meet

**Comment by meet-bhagdev** [comment]
Hello @theodorejb,
Our most recent [release](https://github.com/Azure/msphpsql/releases/tag/v4.0.4) aims to provide a fix for this issue. Give the latest binaries a shot and keep us posted.
A quick note: Validity of  a closed connection or statement should be checked using is_resource() function not by comparing to null.

**Comment by theodorejb** [comment]
The latest release seems to behave the same. The above script still outputs:

```
string(6) "result"
resource(5) of type (Unknown)
```

This isn't a problem for me though, since you previously noted that this is expected behavior and I already updated my code to use an `is_resource()` check.

**Comment by meet-bhagdev** [comment]
Makes sense! This is expected behavior and your understanding is correct. I will close this issue. Feel free to re open if you have questions/concerns.
