### ISSUE TITLE
PHP 7 PDO x64 Driver and integer output parameters

### ISSUE THREAD

**Issue by qqzm** [Azure/msphpsql#86]
I'm seeing an issue with the new PHP7 PDO x64 driver and integer output parameters.

I have an output parameter declared as INT in sql server and PDO::PARAM_INT in PHP.
Somewhere along the line it seems to get converted to an unsigned int. So if I try to return -1 it ends-up as 4294967295 (2^32-1). With the old PHP 5.6 driver it returns -1 as expected.

Sample code to reproduce (returns 4294967295 on PHP7, when -1 is expected):
```
CREATE PROCEDURE sp_Test
	@ErrorNumber INT = 0 OUTPUT
AS
BEGIN
	SET @ErrorNumber = -1
	SELECT 1,2,3
END
GO

<?php 
$dbInfo = array("SQLServer" => "", "SQLDatabase" => "", "Username" => "", "Password" => "");
$db = new PDO("sqlsrv:Server=" . $dbInfo['SQLServer'] . ";Database=" . $dbInfo['SQLDatabase'], $dbInfo['Username'], $dbInfo['Password']);
$stmt = $db->prepare("{CALL sp_Test (:errornumber)}");
$errorNumber = 0;
$stmt->bindParam('errornumber', $errorNumber, PDO::PARAM_INT|PDO::PARAM_INPUT_OUTPUT, 4);
$stmt->execute();
$result = $stmt->fetchAll(PDO::FETCH_NUM);
print("Error Number: $errorNumber\n\n");
print_r($result);
?>

**Comment by meet-bhagdev** [comment]
Hello @qqzm We were able to repro this. We will work towards fixing it.

**Comment by qqzm** [comment]
Just to update on this: I've upgraded to version 4.0.4 of the driver and the bug is still present.

**Comment by meet-bhagdev** [comment]
Hi @qqzm this should be fixed with our latest release. Can you download the [latest binaries](https://github.com/Azure/msphpsql/releases/tag/v4.0-RC) and give it a shot? Thanks

**Comment by qqzm** [comment]
Yep, have tried this and can confirm it is now fixed. Thanks!
