### ISSUE TITLE
PDO Driver handling of booleans

### ISSUE THREAD

**Issue by meet-bhagdev** [Azure/msphpsql#93]
Selects are not working with booleans in filter.

Here is pdo statement debug dump params:

SQL: [133] SELECT * FROM [Scripts] WHERE ([Hidden]=:qp0) AND ([TaggedRemoved]=:qp1) ORDER BY (SELECT NULL) OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY
Params: 2
Key: Name: [4] :qp0
paramno=0
name=[4] ":qp0"
is_param=1
param_type=5
Key: Name: [4] :qp1
paramno=1
name=[4] ":qp1"
is_param=1
param_type=5
I also tried \PDO::PARAM_INT, not working on "bit" datatype column.

https://github.com/cakephp/cakephp/issues/8674

**Comment by KyleWiering** [comment]
Inserts statements with PDO::PARAM_BOOL as the type also seem to fail (everything is true).  Casting the bools to int and using PDO::PARAM_INT is my current work-around.
