### ISSUE TITLE
php-cgi.exe crashes when receiving large amount of data

### ISSUE THREAD

**Issue by meet-bhagdev** [Azure/msphpsql#94]
I'm using Apache 2.4 with php 7.0.6, both MSVC14 x64 and runing under windows 7 x64.
On my main website when I make a select statement which return a large amout of data, php-cgi.exe dies when I'm under fcgid mod and Apache.exe dies when I'm in mod_php.

Apache log :
[fcgid:warn] pid 8928:tid 1440The pipe has been ended. : [client ::1:53113] mod_fcgid: get overlap result error
[core:error] [pid 8928:tid 1440] [client ::1:53113] End of script output before headers: app.php

Windows event log :
Nom de l’application défaillante php-cgi.exe, version : 7.0.6.0, horodatage : 0x57227745
Nom du module défaillant : php7ts.dll, version : 7.0.6.0, horodatage : 0x57227f4d
Code d’exception : 0xc00000fd
Décalage d’erreur : 0x00000000001c34b4
ID du processus défaillant : 0x7bc
Heure de début de l’application défaillante : 0x01d1a9bbab5fe0a8
Chemin d’accès de l’application défaillante : C:\php\php-cgi.exe
Chemin d’accès du module défaillant: C:\php\php7ts.dll
ID de rapport : eb955272-15ae-11e6-b84b-08002700e8d1

**Comment by meet-bhagdev** [comment]
@christophe77 Can you share a repro script with us?

**Comment by christophe77** [comment]
It's used with a symfony 2 API, I'll try to reproduce the same issue with a regular script and I'll share it here.

**Comment by christophe77** [comment]
After some tests the problem appears to occure when I use the Doctrine QueryBuilder with the operator "andWhere".
Crashes : 
`public function getSQLresults(ParamFetcher $filters) {
		$queryBuilder = $this->db_sql->createQueryBuilder();
		$queryBuilder->select('*');
		$queryBuilder->from('MySQLtable', 'mst');

		$queryBuilder
			->where('First = :first')->setParameter('first', 0)
			->andWhere('Second = :second')->setParameter('second', 1)
			->andWhere('Third = :third')->setParameter('third', 0);
			
		if($filters->get('dateFrom') && $filters->get('dateTo'))
			$queryBuilder
				->andWhere('Fourth BETWEEN :dateFrom AND :dateTo')
				->setParameter('dateFrom', $filters->get('dateFrom'))
				->setParameter('dateTo', $filters->get('dateTo'));
			
		try {
        	$SQLresults = $queryBuilder->execute();
        } catch (Exception $e) {
        	return new Exception("Bad Request");
        }

        $results = $SQLresults->fetchAll();
		return $results;
        $trucksArray = array();
}`

Works : 
`public function getSQLresults(ParamFetcher $filters) {
		$queryBuilder = $this->db_sql->createQueryBuilder();
		$queryBuilder->select('*');
		$queryBuilder->from('MySQLtable', 'mst');			
		$queryBuilder
			->where('First = 0 AND Second = 1 AND Third = 0 AND Fourth BETWEEN :dateFrom AND :dateTo')
			->setParameter('dateFrom', $filters->get('dateFrom'))
			->setParameter('dateTo', $filters->get('dateTo'));
			
		try {
        	$SQLresults = $queryBuilder->execute();
        } catch (Exception $e) {
        	return new Exception("Bad Request");
        }

        $results = $SQLresults->fetchAll();
		return $results;
        $trucksArray = array();
}`

Maybe you can rename the issue as it's not really the good title now ;-)

**Comment by christophe77** [comment]
problem solved with the upgrade of "Doctrine".

**Comment by meet-bhagdev** [comment]
Awesome :) I will close this bug.
