### ISSUE TITLE
PDOStatement object has not been successfully released

### ISSUE THREAD

**Issue by sp-ice** [Azure/msphpsql#97]
Hello

PDOStatement object has not been successfully released.
Memory leak occurs in the following code.

```
<?php

$dns = 'sqlsrv:Server=xxx.xxx.xxx.xxx;Database=ms_dbname';
$db = new PDO($dns_old, 'ms_username', 'ms_password', array()); 
$tables = array(
	'table_name1',
	'table_name2',
	'table_name3',
	'table_name4',
	//…
);

foreach ($tables as $table_name) {
	$sql = "SELECT * FROM \"{$table_name}\";";
	$stmt = $db->prepare($sql);
	$stmt->execute();
	while (($row = $stmt->fetch(PDO::FETCH_ASSOC)) !== false) {
	}
	$stmt->closeCursor();
	unset($stmt);
}
```

I tried in the following environment.
* PHP v7.0.6(Non Thread Safe)
* PDO v4.0.4

Looking forward to the next release.

Daisuke Uno

**Comment by jomisacu** [comment]
you should use != instead of !== or simply remove "!== false" from condition

**Comment by sp-ice** [comment]
@jomisacu Thanks!
I tyied again in the following code, But Memory leak occurs yet.

```
while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
```

**Comment by meet-bhagdev** [comment]
@sp-ice This issue should be fixed in our RTW release: https://github.com/Azure/msphpsql/releases/tag/v4.0-RTW.
Can you help us verify that it is fixed?

**Comment by sp-ice** [comment]
@meet-bhagdev Thanks!
I tyied again on v4.0.6 and verified that it is fixed.
