### ISSUE TITLE
Login Failes for all users

### ISSUE THREAD

**Issue by 4DallasC** [Azure/msphpsql#98]
I was using the 5.3 version with SQLExpress and everything worked smoothly. I upgraded to PHP7, which required the new sqlsrv extension. This than demanded the ODBC Driver 11 for SQL Server.

Now with all the same previous usernames and database names I get the following error:-
error 1: 'code' => 18456, 'message' => "[Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Login failed for user 'IIS APPPOOL\DefaultAppPool'."
error 2: 'code' => 4060, 'message' => "[Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Cannot open database "databasename" requested by the login. The login failed."

I tried creating an ODBC connection and connecting via Visual Studio and it worked fine.
I tried "GRANT ALL TO [IIS APPPOOL\DefaultAppPool]" and it didn't help

**Comment by 4DallasC** [comment]
Oh, I have to open up the database like a hooker with:-
GRANT CONNECT TO guest
GRANT CONTROL TO public

**Comment by meet-bhagdev** [comment]
@4DallasC I will mark this issue closed. Feel free to open it if you have more questions 👍
