### ISSUE TITLE
Use of undefined constant

### ISSUE THREAD

**Issue by sirio3mil** [Azure/msphpsql#99]
In previous versions of driver for prior PHP I could use the following constants which are no longer defined, They will be reinstate or will be replaced by others? If they are replaced, what is the new nomenclature?

SQL_BIGINT
SQL_INTEGER
SQL_SMALLINT
SQL_TINYINT
SQL_BIT
SQL_DECIMAL
SQL_FLOAT
SQL_NUMERIC
SQL_REAL

Regards

**Comment by MCF** [comment]
I think there was some discussion of these constants in this issue:

https://github.com/Azure/msphpsql/issues/87
